spring:
  application:
    name: Product-Service
  config:
    activate:
      on-profile: prod
  cache:
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

otel:
  service:
    name: "product-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"

server:
  port: 7070

redisson:
  host: 127.0.0.1
  port: 6379

s3:
  access-key: b0a085fad6914c2abd49b762ee2263e2
  secret-key: 2bd487564bb54e9a8231bb3944108971
  region: ru-7
  bucket-name: stroy1click

resilience4j:
  ratelimiter:
    instances:
      storageLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
      productLimiter:
        limitForPeriod: 30
        limitRefreshPeriod: 1s
      categoryLimiter:
        limit-for-period: 30
        limitRefreshPeriod: 1s
      subcategoryLimiter:
        limit-for-period: 30
        limitRefreshPeriod: 1s
      productTypeLimiter:
        limit-for-period: 30
        limitRefreshPeriod: 1s
      attributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
      productTypeAttributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
      productAttributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s