spring:
  application:
    name: Catalog-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  cache:
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

otel:
  service:
    name: "product-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"

server:
  port: 7070

redisson:
  host: 127.0.0.1
  port: 6379
  username: default
  password: password

url:
  search: http://localhost:4045/api/v1/search

s3:
  access-key: b0a085fad6914c2abd49b762ee2263e2
  secret-key: 2bd487564bb54e9a8231bb3944108971
  region: ru-7
  bucket-name: stroy1click

resilience4j:
  ratelimiter:
    instances:
      storageLimiter:
        limitForPeriod: 30
        limitRefreshPeriod: 1s
      productLimiter:
        limitForPeriod: 30
        limitRefreshPeriod: 1s
      categoryLimiter:
        limit-for-period: 30
        limitRefreshPeriod: 1s
      subcategoryLimiter:
        limit-for-period: 30
        limitRefreshPeriod: 1s
      productTypeLimiter:
        limit-for-period: 30
        limitRefreshPeriod: 1s
      attributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
      productTypeAttributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
      productAttributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
  circuitbreaker:
    instances:
      outboxClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always